name       : conky
version    : 1.9.0
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/conky/conky/1.9.0/conky-1.9.0.tar.gz : 1de754d77b2671f68795fdb9fc506328a1668dd6ca00984c3f49790a66d368ca
license    : GPL
summary    : Lightweight system monitor for X
description: |
    Lightweight system monitor for X
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(x11)
    - pkgconfig(imlib2)
    - pkgconfig(lua-5.1)
    - pkgconfig(cairo)
    - pkgconfig(xext)
    - pkgconfig(xdamage)
    - pkgconfig(xft)
    - pkgconfig(libcurl)
    - pkgconfig(libxml-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
