name       : conky
version    : 1.10.6
release    : 10
source     :
    - https://github.com/brndnmtthws/conky/archive/v1.10.6.tar.gz : 4c80982960b2a72e3e33cef33347c97b9239ed110d9584da4e7f17f28faf60ca
license    :
    - GPL-3.0
    - BSD-3-Clause
summary    : Lightweight system monitor for X
component  : desktop.util
description: |
    Lightweight system monitor for X
builddeps  :
    - git
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(lua-5.1)
    - pkgconfig(x11)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xft)
    - pkgconfig(xinerama)
    - wireless-tools-devel
setup      : |
    mkdir build
    pushd build
    %cmake -D CMAKE_BUILD_TYPE=Release \
           -D BUILD_WLAN=ON \
           -D BUILD_XDBE=ON \
           -D BUILD_IMLIB2=ON \
           -D BUILD_NCURSES=OFF \
           -D BUILD_CURL=ON \
           -D BUILD_RSS=ON \
           -D BUILD_PULSEAUDIO=ON ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
