name       : conky
version    : 1.10.2
release    : 7
source     :
    - https://github.com/brndnmtthws/conky/archive/v1.10.2.tar.gz : cc4536141d90a6403a1eccf1f36891b6dd421e69ec3803842c65113c3a109cf0
license    : GPL
summary    : Lightweight system monitor for X
description: |
    Lightweight system monitor for X
component  : desktop.util
builddeps  :
    - git
    - pkgconfig(cairo)
    - pkgconfig(glib-2.0)
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libxml-2.0)
    - pkgconfig(lua-5.1)
    - pkgconfig(x11)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xft)
    - pkgconfig(xinerama)
    - toluapp-devel
    - wireless-tools-devel
setup      : |
    mkdir build && cd build
    %cmake .. -DBUILD_IMLIB2=ON -DBUILD_CURL=ON -DBUILD_LUA_CAIRO=ON -DBUILD_LUA_IMLIB2=ON -DBUILD_RSS=ON -DBUILD_WLAN=ON
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
