name       : conky
version    : 1.11.1
release    : 17
source     :
    - https://github.com/brndnmtthws/conky/archive/v1.11.1.tar.gz : 71fab859946cc2e67be46f2db53859c66369c5c87acf18fc8dfbd41b114f6d6e
license    :
    - GPL-3.0-or-later
    - BSD-3-Clause
summary    : Lightweight system monitor for X
description: |
    Lightweight system monitor for X
component  : desktop.util
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libical)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(lua-5.1)
    - pkgconfig(x11)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xft)
    - pkgconfig(xinerama)
    - toluapp-devel
    - wireless-tools-devel
    - git
setup      : |
    export CXXFLAGS="$CXXFLAGS -I/usr/include/lua5.1"
    %cmake -DBUILD_CURL=1 \
           -DBUILD_ICAL=1 \
           -DBUILD_ICONV=1 \
           -DBUILD_JOURNAL=1 \
           -DBUILD_LUA_CAIRO=1 \
           -DBUILD_LUA_IMLIB2=1 \
           -DBUILD_LUA_RSVG=1 \
           -DBUILD_PULSEAUDIO=1 \
           -DBUILD_RSS=1 \
           -DBUILD_WLAN=1 .
build      : |
    %make
install    : |
    %make_install
