name       : conky
version    : 1.11.5
release    : 21
source     :
    - https://github.com/brndnmtthws/conky/archive/v1.11.5.tar.gz : 4cefdd92219a90934c28297e4ac7448a3f69d6aeec5d48c5763b23f6b214ef13
license    :
    - GPL-3.0-or-later
    - BSD-3-Clause
summary    : Lightweight system monitor for X
description: |
    Lightweight system monitor for X
component  : desktop.util
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libical)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(lua)
    - pkgconfig(x11)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xft)
    - pkgconfig(xinerama)
    - toluapp-devel
    - wireless-tools-devel
    - git
setup      : |
    export CXXFLAGS="$CXXFLAGS -I/usr/include/lua5.1"
    %cmake_ninja -DBUILD_CURL=1 \
           -DBUILD_ICAL=1 \
           -DBUILD_ICONV=1 \
           -DBUILD_JOURNAL=1 \
           -DBUILD_LUA_CAIRO=1 \
           -DBUILD_LUA_IMLIB2=1 \
           -DBUILD_LUA_RSVG=1 \
           -DBUILD_PULSEAUDIO=1 \
           -DBUILD_RSS=1 \
           -DBUILD_WLAN=1 .
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -r $installdir/usr/lib/libtcp-portmon.a
