name       : conky
version    : 1.9.0
release    : 15
source     :
    - https://kent.dl.sourceforge.net/project/conky/conky/1.9.0/conky-1.9.0.tar.gz : 1de754d77b2671f68795fdb9fc506328a1668dd6ca00984c3f49790a66d368ca
license    :
    - GPL-3.0-or-later
    - BSD-3-Clause
summary    : Lightweight system monitor for X
description: |
    Lightweight system monitor for X
component  : desktop.util
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(glib-2.0)
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libxml-2.0)
    - pkgconfig(lua-5.1)
    - pkgconfig(x11)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xft)
    - toluapp-devel
    - wireless-tools-devel
setup      : |
    export CFLAGS="$CFLAGS -I/usr/include/lua5.1"
    sed -i "s|tolua++ |toluapp |g" configure*
    %configure --disable-static \
        --enable-imlib2 \
        --enable-wlan \
        --enable-lua-imlib2 \
        --enable-lua-cairo \
        --enable-curl \
        --enable-rss \
        --enable-wlan
build      : |
    export CFLAGS="$CFLAGS -I/usr/include/lua5.1"
    %make
install    : |
    export CFLAGS="$CFLAGS -I/usr/include/lua5.1"
    %make_install
