name       : conky
version    : 1.11.1
release    : 16
source     :
    - https://github.com/brndnmtthws/conky/archive/v1.11.1.tar.gz : 71fab859946cc2e67be46f2db53859c66369c5c87acf18fc8dfbd41b114f6d6e
license    :
    - GPL-3.0-or-later
    - BSD-3-Clause
summary    : Lightweight system monitor for X
description: |
    Lightweight system monitor for X
component  : desktop.util
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(glib-2.0)
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libxml-2.0)
    - pkgconfig(lua-5.3)
    - pkgconfig(x11)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xft)
    - pkgconfig(xinerama)
    - wireless-tools-devel
    - git
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
